### ISSUE TITLE
Warning: The network does not appear to fully agree! Some miners appear to be experiencing issues.

### ISSUE THREAD

**Issue by erasmospunk** [digibyte/digibyte#38]
At least once per day the wallet/node becomes unusable due to this bug. RPC calls like `getblockhash` return the following error:

```
{
  "result": null,
  "error": {
    "code": -2,
    "message": "Safe mode: Warning: The network does not appear to fully agree! Some miners appear to be experiencing issues."
  },
  "id": "jsonrpc"
}
```

Check here the [debug.log](http://pastebin.com/6N0VnNbk).

We use the latest 3.0.3 version. I spoke with a developer from ShapeShift and he also mentioned that this bug affects them. This is the same issue as reported in #27.

**Comment by MentalCollatz** [comment]
This should be fixed by the new work calculation in 2839671abd9807b39a4f8a2a8f52ee939c07ab43

**Comment by flound1129** [comment]
This is also affecting Multipool users, our payout wallet becomes disabled at least once per day due to this.  Can we please get a release soon that addresses this issue?

**Comment by erasmospunk** [comment]
@MentalCollatz any ETA for the official fix?

**Comment by terrylai** [comment]
Will be released soon.

**Comment by rootdude** [comment]
Do we have an update on this at all @MentalCollatz? I added:

checkblocks=10
checklevel=1

To digibyte.conf as a workaround (I think) but this should be addressed??

**Comment by flound1129** [comment]
I doubt those settings would have any effect on this issue because they only affect startup behavior.  We need to know exactly what patches to apply so we can compile ourselves or a release.

**Comment by flound1129** [comment]
Any news on the release?

**Comment by digibyte** [comment]
The master branch (v4.0.0) should fix this when we reach block 1,430,000 in a couple days.

**Comment by daygle** [comment]
Still happening for me too, even on master and over block 1430000.

**Comment by Metice** [comment]
Still safe mode for me (on 3 wallets).

**Comment by terrylai** [comment]
Block chain fork is intrinsic in DigiByte as it uses block chain technology like Bitcoin. 4.0 version actually increases the propagation speed of blocks and so it decreases the chance of block chain fork.

For working around, if your wallet is used by server, you can write a simple script to monitor safe mode inside logs or inside "digibyted getinfo" and reset server if safe mode is entered.

**Comment by digibyte** [comment]
We are updating to 4.0.1 which disconnects all v3.0 peers and bumps to 70003

**Comment by flound1129** [comment]
My 4.0.1 is not connecting to anyone, need some addnodes please

**Comment by Metice** [comment]
This nodes are currently connected to my wallets
"188.165.223.132:12024",
"149.202.44.159:12024",
"212.129.1.77:12024",
"108.61.10.90:12024",
"45.79.10.59:12024",
"176.31.126.191:12024",
"89.173.225.88:12024",
"82.38.241.21:12024",
"216.250.125.121:12024"

**Comment by flound1129** [comment]
Those are working thanks.
